// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwvSu_bKiITrVixkKWO1JecYbEduXvDZ0',
    appId: '1:225000473469:web:7f7443f970eb17ec108214',
    messagingSenderId: '225000473469',
    projectId: 'speedchap-b036b',
    authDomain: 'speedchap-b036b.firebaseapp.com',
    storageBucket: 'speedchap-b036b.appspot.com',
    measurementId: 'G-17E6KB8KGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrr8d8JcRgt9BaRmoAujB7b-Vo58Pcjy4',
    appId: '1:225000473469:android:297cdd130d3429b0108214',
    messagingSenderId: '225000473469',
    projectId: 'speedchap-b036b',
    storageBucket: 'speedchap-b036b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7rPyPv4HycuCItXIpVwenWf4j3I32bWE',
    appId: '1:225000473469:ios:f0de2759d8e7a729108214',
    messagingSenderId: '225000473469',
    projectId: 'speedchap-b036b',
    storageBucket: 'speedchap-b036b.appspot.com',
    iosClientId: '225000473469-hcoek7vgv5bdcm0tli1o82oosfmkii0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7rPyPv4HycuCItXIpVwenWf4j3I32bWE',
    appId: '1:225000473469:ios:ccc69167e997b20a108214',
    messagingSenderId: '225000473469',
    projectId: 'speedchap-b036b',
    storageBucket: 'speedchap-b036b.appspot.com',
    iosClientId: '225000473469-lhokh3jr89ef198cdvkmfe205scqsace.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedchat.RunnerTests',
  );
}
